### ISSUE TITLE
New page for Trump Action for wednesday 

### ISSUE THREAD

**Issue by carlosweb2000** [Cosecha/cosecha.github.io#14]
## User Story

This should also be the title of the issue:

The link should be: movimientocosecha.com/builtbyus

> “As a [user type], I want to [task] so that [goal].”
- **User Story:** [user type]
- **Task:** [task]
- **Goal:** [goal]
## Definition of Done

Content:
[(https://docs.google.com/document/d/1zCCqPU3IhEI-XJn5NsSVfbmae3adeyLhTh1s_xwgQTo/edit?ts=57c48a35)]

Thirty- five years ago, Trump Tower was built by 200 undocumented immigrants paid $5 a day, if that! Despite having relied on our labor to make his millions, Donald Trump has the audacity to base his presidential platform on hate, racism, and ignorance against the immigrant community. Cosecha is here to highlight the hypocrisy of the anti-immigrant sentiment that is resonating with the American public in the moments leading up to the 2016 November elections. Trump is not the first, and won’t be the last, public figure to make a political career based on the scapegoating of immigrant communities. Cosecha is here to channel the fear and frustration existent within the immigrant community into action. We want to send the American public a message: this country was built by us, so we will use our labor and consumer power to demand permanent protection, dignity, and respect for our immigrant community. 

```
        Immigrants Confront Trump & Reclaim Dignity
```

On August 31, 2016, ten immigrants led a civil disobedience at Trump Tower to send the message that the tower, and this country, was #BuiltByUs. We are the pillars that holds this country up, and without us, it will fall. As immigrants, we feel a burning indignation when we listen to politicians, the media, and Trump supporters give reasons why we should be deported; why our families should be separated; why our contributions to this country hold no value. We can no longer be silent as we listen to hatred and xenophobia in the airwaves. Instead, Cosecha will amplify the voices of our people-- of our struggles, pains, and hope for the future to reclaim dignity & respect for ourselves and win permanent protection for our people. 

Stand with Cosecha as we lead a national public confrontation against hate, racism, and xenophobia. 

Join Our Movement

Pledge to Risk Arrest for Cosecha

Sign Up to An Anti-Trump Initiation Training

Contact Us (map, facebook, telegram)

Donate

**Comment by celsom3** [comment]
@carlosweb2000 just to confirm that the url should be /builtbyus. Or would /built-by-us work better?

**Comment by carlosweb2000** [comment]
yes, that is correct movimientocosecha.com/builtbyus

**Comment by celsom3** [comment]
@carlosweb2000 I just merged the changes with the master branch, and the page should be live at http://movimientocosecha.com/builtbyus
