### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by celsom3** [Cosecha/cosecha.github.io#2]
Need some help to translate the site to Portuguese.

**Comment by thaismarques** [comment]
Can you make me a pt.js for the portuguese translation and give me access?

**Comment by celsom3** [comment]
Yes, @thaismarques here is the link to that file:

https://github.com/Cosecha/cosecha.github.io/blob/master/_harp/public/i18n/pt.js

I'll go ahead and assign this issue to you. Thanks for working on this! :-)

**Comment by thaismarques** [comment]
Hey! Which option do I choose after inputing the edits?

Commit directly to the master branch.
 Create a new branch for this commit and start a pull request. Learn more
about pull requests. https://help.github.com/articles/using-pull-requests
Commit changes Cancel
https://github.com/Cosecha/cosecha.github.io/blob/master/_harp/public/i18n/tl.js

**Comment by celsom3** [comment]
I think creating a pull request is the best way to go @thaismarques

**Comment by celsom3** [comment]
Create a pull request
