### ISSUE TITLE
Change Builtbyus page "Join our movement" and "donate" to have buttons at the top of the page

### ISSUE THREAD

**Issue by carlosweb2000** [Cosecha/cosecha.github.io#21]
put the "join our movement" and "donate" buttons far enough up on the page so that they can be seen without scrolling down.  Also make them bigger and the fonts bold so they pop against the cover/top photo

**Comment by thaismarques** [comment]
also can we replace the photo that is on the /builtby us with this photo?
![14203312_1778418555764435_2736263474814413573_n](https://cloud.githubusercontent.com/assets/20777219/18352787/c581454a-75ad-11e6-92bb-7aba1675173b.jpg)

**Comment by celsom3** [comment]
I have a small window today. I'll be working on it in the next hour.
