### ISSUE TITLE
Top Menu Text Hard to Read

### ISSUE THREAD

**Issue by sfentress** [Cosecha/cosecha.github.io#25]
The tan-colored text on the top border is very difficult to read, as it is the same color as the image in places:

<img width="1409" alt="screen shot 2016-11-27 at 9 39 24 pm" src="https://cloud.githubusercontent.com/assets/35721/20654880/3f2a9f96-b4eb-11e6-9201-506b6c6a7b9c.png">

If you want to keep the color scheme, I'd suggest a very subtle darkening of the area behind the text with a text-shadow, and a slight lightening of the text.

<img width="1409" alt="screen shot 2016-11-27 at 9 47 27 pm" src="https://cloud.githubusercontent.com/assets/35721/20654909/8fb8c06e-b4eb-11e6-8286-8d7680d6731a.png">

```
#headerNav nav {
    color: #dac68b;
    text-shadow: 0px 0px 12px #000;
}
````

**Comment by celsom3** [comment]
Thanks for the issue submission @sfentress. I haven't been involved in Cosecha's digital work as much as before, but I think the website has been moved to Squarespace.

I'm not sure what processes there are for open source collaboration are these days, so I'll ask some folks by tagging them here. That way, if you are interested in participating in whatever capacity, they can more appropriately let you know how. 😄 

@Cosecha/cosecha-dev-village @Cosecha/organizers @ghortiz-pena
